import type { Sql } from "postgres";
import type { ActionGraph, CursorPage, LogChunk, OrganizationSummary, OverviewDto, RepositorySummary, RunDetail, RunJob, RunStage, RunSummary, WorkerDetail } from "@whitesmith/contracts";

export type DashboardDb = Sql<{}>;
export type RunTransition = { status: RunSummary["status"]; conclusion: RunSummary["conclusion"]; startedAt?: string | null; completedAt?: string | null };
const statusOrder: Record<RunSummary["status"], number> = { queued: 0, in_progress: 1, completed: 2 };
const terminalConclusions = new Set(["success", "failure", "cancelled", "skipped", "neutral"]);
export function monotonicTransition(current: RunTransition, next: RunTransition): RunTransition {
  if (current.status === "completed" || terminalConclusions.has(current.conclusion ?? "")) return current;
  if (statusOrder[next.status] < statusOrder[current.status]) return current;
  return { ...current, ...next };
}
export function boundedLogChunks(chunks: LogChunk[], limit: number): { items: LogChunk[]; hasMore: boolean } {
  const safeLimit = Math.max(0, Math.min(1000, Math.floor(limit)));
  return { items: chunks.slice(0, safeLimit).map(chunk => ({ ...chunk, content: chunk.content.slice(0, 256 * 1024) })), hasMore: chunks.length > safeLimit };
}
export function cursorBoundary<T extends { id: string }>(items: T[], cursor: string | null, limit: number): CursorPage<T> {
  const start = cursor ? Math.max(0, items.findIndex(item => item.id === cursor) + 1) : 0;
  const page = items.slice(start, start + Math.max(0, limit));
  return { items: page, nextCursor: start + page.length < items.length && page.length ? page.at(-1)!.id : null };
}

export async function listOrganizations(db: DashboardDb, userId: string): Promise<OrganizationSummary[]> {
  return await db<OrganizationSummary[]>`SELECT o.id, o.login AS name, o.login, m.role, (SELECT count(*)::int FROM dashboard_repositories r WHERE r.organization_id=o.id) AS "repositoryCount", (SELECT count(*)::int FROM workers w WHERE w.organization_id=o.id) AS "workerCount" FROM organizations o JOIN memberships m ON m.organization_id=o.id WHERE m.user_id=${userId} ORDER BY o.login`;
}
export async function getOverview(db: DashboardDb, organizationId: string, period: OverviewDto["period"]): Promise<OverviewDto> {
  const [row] = await db<OverviewDto[]>`SELECT ${organizationId}::text AS "organizationId", ${period}::text AS period, count(*) FILTER (WHERE status='queued')::int AS queued, count(*) FILTER (WHERE status='in_progress')::int AS running, count(*) FILTER (WHERE status='completed' AND conclusion='success')::int AS completed, count(*) FILTER (WHERE status='completed' AND conclusion <> 'success')::int AS failed, 0::int AS "queueP50Ms", 0::int AS "queueP95Ms", 0::int AS "durationP50Ms", 0::int AS "durationP95Ms", 0::int AS concurrency, 0::float AS utilization FROM dashboard_runs WHERE organization_id=${organizationId} AND queued_at >= now() - CASE ${period} WHEN '24h' THEN interval '24 hours' WHEN '7d' THEN interval '7 days' ELSE interval '30 days' END`;
  return { ...row, utilization: { vcpu: 0, memory: 0, storage: 0, pods: 0 } };
}
export async function listRepositories(db: DashboardDb, organizationId: string, limit = 50): Promise<CursorPage<RepositorySummary>> { const rows = await db<RepositorySummary[]>`SELECT id, organization_id AS "organizationId", name, full_name AS "fullName", is_private AS private, installation_id AS "installationId", i.approved FROM dashboard_repositories r JOIN dashboard_installations i ON i.organization_id=r.organization_id AND i.id=r.installation_id WHERE r.organization_id=${organizationId} ORDER BY r.full_name LIMIT ${limit + 1}`; return { items: rows.slice(0, limit), nextCursor: rows.length > limit ? rows[limit - 1].id : null }; }
export async function listRuns(db: DashboardDb, organizationId: string, limit = 50): Promise<CursorPage<RunSummary>> { const rows = await db<RunSummary[]>`SELECT r.id, r.organization_id AS "organizationId", r.repository_id AS "repositoryId", p.name AS "repositoryName", r.run_number AS "runNumber", r.workflow_name AS "workflowName", r.event, r.branch, r.commit_sha AS "commitSha", r.actor_login AS "actorLogin", r.status, r.conclusion, r.queued_at AS "queuedAt", r.started_at AS "startedAt", r.completed_at AS "completedAt", 0::bigint AS "durationMs", r.runtime_boundary AS "runtimeBoundary" FROM dashboard_runs r JOIN dashboard_repositories p ON p.organization_id=r.organization_id AND p.id=r.repository_id WHERE r.organization_id=${organizationId} ORDER BY r.queued_at DESC, r.id DESC LIMIT ${limit + 1}`; return { items: rows.slice(0, limit), nextCursor: rows.length > limit ? rows[limit - 1].id : null }; }
export async function getRunDetail(db: DashboardDb, organizationId: string, runId: string): Promise<RunDetail | null> { const [run] = await listRuns(db, organizationId, 1000).then(page => page.items.filter(x => x.id === runId)); if (!run) return null; const jobs = await db<RunJob[]>`SELECT id,name,status,conclusion,stage,runner_name AS "runnerName",requested,observed FROM dashboard_jobs WHERE organization_id=${organizationId} AND run_id=${runId} ORDER BY id`; const edges = await db<{from:string;to:string}[]>`SELECT from_job_id AS from,to_job_id AS to FROM dashboard_action_edges WHERE organization_id=${organizationId} AND run_id=${runId}`; return { ...run, jobs, actionGraph: { nodes: jobs.map(job => ({ id: job.id, name: job.name, status: job.stage })), edges } as ActionGraph }; }
export async function listLogChunks(db: DashboardDb, organizationId: string, runId: string, jobId: string, after = -1, limit = 100): Promise<CursorPage<LogChunk>> { const rows = await db<LogChunk[]>`SELECT organization_id AS "organizationId", run_id AS "runId", job_id AS "jobId", sequence, content, false AS "hasMore", occurred_at AS "occurredAt" FROM dashboard_log_chunks WHERE organization_id=${organizationId} AND run_id=${runId} AND job_id=${jobId} AND sequence>${after} ORDER BY sequence LIMIT ${limit + 1}`; return { items: rows.slice(0, limit).map(x => ({ ...x, hasMore: rows.length > limit })), nextCursor: rows.length > limit ? String(rows[limit - 1].sequence) : null }; }
export async function listWorkers(db: DashboardDb, organizationId: string, limit = 50): Promise<CursorPage<WorkerDetail>> { const rows = await db<WorkerDetail[]>`SELECT id, organization_id AS "organizationId", name, platform, 'kata-k3s' AS driver, admission_state AS "admissionState", connection_state AS "connectionState", configuration_state AS "configurationState", fingerprint, limits, doctor, jsonb_build_object('vcpu',jsonb_build_object('actual',1,'reserved',0,'free',1),'memoryBytes',jsonb_build_object('actual',1,'reserved',0,'free',1),'storageBytes',jsonb_build_object('actual',1,'reserved',0,'free',1),'pods',jsonb_build_object('actual',1,'reserved',0,'free',1)) AS capacity, 0 AS "activeSandboxes", false AS draining FROM workers WHERE organization_id=${organizationId} ORDER BY name LIMIT ${limit + 1}`; return { items: rows.slice(0, limit), nextCursor: rows.length > limit ? rows[limit - 1].id : null }; }
export async function getWorkerDetail(db: DashboardDb, organizationId: string, workerId: string): Promise<WorkerDetail | null> { const page = await listWorkers(db, organizationId, 1000); return page.items.find(worker => worker.id === workerId) ?? null; }
export async function recordRunTransition(db: DashboardDb, organizationId: string, runId: string, transition: RunTransition): Promise<void> { await db`UPDATE dashboard_runs SET status=${transition.status}, conclusion=${transition.conclusion}, started_at=COALESCE(${transition.startedAt ?? null}, started_at), completed_at=COALESCE(${transition.completedAt ?? null}, completed_at) WHERE organization_id=${organizationId} AND id=${runId} AND status <> 'completed' AND (status='queued' OR ${transition.status} <> 'queued')`; }
export async function recordRunStage(db: DashboardDb, organizationId: string, runId: string, stage: RunStage): Promise<void> { await db`INSERT INTO dashboard_run_stages (organization_id,run_id,stage) VALUES (${organizationId},${runId},${stage}) ON CONFLICT DO NOTHING`; }
