import React from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";
import { flexRender, getCoreRowModel, useReactTable, type ColumnDef } from "@tanstack/react-table";

type Worker={id:string;name:string;platform:string;admissionState:string;connectionState:string;configurationState:string;fingerprint?:string};
const queryClient=new QueryClient({defaultOptions:{queries:{staleTime:10_000}}});
function Workers(){ const query=useQuery({queryKey:["workers"],queryFn:async()=>{const response=await fetch("/api/workers");if(!response.ok)throw new Error("Unable to load workers");return response.json() as Promise<Worker[]>}}); const columns:ColumnDef<Worker>[]=[{accessorKey:"name",header:"Worker"},{accessorKey:"platform",header:"Platform"},{accessorKey:"admissionState",header:"Admission"},{accessorKey:"connectionState",header:"Connection"},{accessorKey:"configurationState",header:"Configuration"},{accessorKey:"fingerprint",header:"Fingerprint"}]; const table=useReactTable({data:query.data??[],columns,getCoreRowModel:getCoreRowModel()}); return <main><header><div><p className="eyebrow">WHITESMITH CONTROL PLANE</p><h1>Runner operations</h1><p>Ephemeral GitHub Actions capacity with explicit VM boundaries.</p></div><a className="button" href="/api/auth/github">Sign in with GitHub</a></header><section className="panel"><div className="section-title"><h2>Workers</h2><span>{query.data?.length??0} enrolled</span></div>{query.isLoading?<p>Loading workers…</p>:query.isError?<p role="alert">{query.error.message}</p>:<table><caption className="sr-only">Workers and their runtime admission state</caption><thead>{table.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(header=><th key={header.id}>{flexRender(header.column.columnDef.header,header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><tr key={row.id}>{row.getVisibleCells().map(cell=><td key={cell.id}>{String(flexRender(cell.column.columnDef.cell,cell.getContext())??cell.getValue()??"—")}</td>)}</tr>)}</tbody></table>}</section></main>}
function App(){return <QueryClientProvider client={queryClient}><Workers/></QueryClientProvider>}
createRoot(document.getElementById("root")!).render(<App/>);
