/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './file-routes/__root'
import { Route as AuthenticatedRouteImport } from './file-routes/_authenticated'
import { Route as OnboardingRouteImport } from './file-routes/onboarding'
import { Route as AuthenticatedIndexRouteImport } from './file-routes/_authenticated/index'
import { Route as AuthenticatedPoolsRouteImport } from './file-routes/_authenticated/pools'
import { Route as AuthenticatedRepositoriesRouteImport } from './file-routes/_authenticated/repositories'
import { Route as AuthenticatedRunsRouteImport } from './file-routes/_authenticated/runs'
import { Route as AuthenticatedSettingsRouteImport } from './file-routes/_authenticated/settings'
import { Route as AuthenticatedWorkersRouteImport } from './file-routes/_authenticated/workers'
import { Route as AuthenticatedRunsIndexRouteImport } from './file-routes/_authenticated/runs/index'
import { Route as AuthenticatedRunsRunIdRouteImport } from './file-routes/_authenticated/runs/$runId'
import { Route as AuthenticatedRunsTimingRouteImport } from './file-routes/_authenticated/runs.timing'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoolsRoute = AuthenticatedPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepositoriesRoute =
  AuthenticatedRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunsRoute = AuthenticatedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkersRoute = AuthenticatedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRunsRoute,
} as any)
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AuthenticatedRunsRoute,
} as any)
const AuthenticatedRunsTimingRoute = AuthenticatedRunsTimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => AuthenticatedRunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pools': typeof AuthenticatedPoolsRoute
  '/repositories': typeof AuthenticatedRepositoriesRoute
  '/runs': typeof AuthenticatedRunsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/runs/timing': typeof AuthenticatedRunsTimingRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/pools': typeof AuthenticatedPoolsRoute
  '/repositories': typeof AuthenticatedRepositoriesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/': typeof AuthenticatedIndexRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/runs/timing': typeof AuthenticatedRunsTimingRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/pools': typeof AuthenticatedPoolsRoute
  '/_authenticated/repositories': typeof AuthenticatedRepositoriesRoute
  '/_authenticated/runs': typeof AuthenticatedRunsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workers': typeof AuthenticatedWorkersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/_authenticated/runs/timing': typeof AuthenticatedRunsTimingRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/pools'
    | '/repositories'
    | '/runs'
    | '/settings'
    | '/workers'
    | '/runs/$runId'
    | '/runs/timing'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/pools'
    | '/repositories'
    | '/settings'
    | '/workers'
    | '/'
    | '/runs/$runId'
    | '/runs/timing'
    | '/runs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/onboarding'
    | '/_authenticated/pools'
    | '/_authenticated/repositories'
    | '/_authenticated/runs'
    | '/_authenticated/settings'
    | '/_authenticated/workers'
    | '/_authenticated/'
    | '/_authenticated/runs/$runId'
    | '/_authenticated/runs/timing'
    | '/_authenticated/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools': {
      id: '/_authenticated/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof AuthenticatedPoolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories': {
      id: '/_authenticated/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AuthenticatedRepositoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs': {
      id: '/_authenticated/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workers': {
      id: '/_authenticated/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthenticatedWorkersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRunsRoute
    }
    '/_authenticated/runs/$runId': {
      id: '/_authenticated/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRunsRoute
    }
    '/_authenticated/runs/timing': {
      id: '/_authenticated/runs/timing'
      path: '/timing'
      fullPath: '/runs/timing'
      preLoaderRoute: typeof AuthenticatedRunsTimingRouteImport
      parentRoute: typeof AuthenticatedRunsRoute
    }
  }
}

interface AuthenticatedRunsRouteChildren {
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute
  AuthenticatedRunsTimingRoute: typeof AuthenticatedRunsTimingRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
}

const AuthenticatedRunsRouteChildren: AuthenticatedRunsRouteChildren = {
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
  AuthenticatedRunsTimingRoute: AuthenticatedRunsTimingRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
}

const AuthenticatedRunsRouteWithChildren =
  AuthenticatedRunsRoute._addFileChildren(AuthenticatedRunsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPoolsRoute: typeof AuthenticatedPoolsRoute
  AuthenticatedRepositoriesRoute: typeof AuthenticatedRepositoriesRoute
  AuthenticatedRunsRoute: typeof AuthenticatedRunsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkersRoute: typeof AuthenticatedWorkersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPoolsRoute: AuthenticatedPoolsRoute,
  AuthenticatedRepositoriesRoute: AuthenticatedRepositoriesRoute,
  AuthenticatedRunsRoute: AuthenticatedRunsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkersRoute: AuthenticatedWorkersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
