import { useRef, useState } from "react";
import { Button } from "@astryxdesign/core/Button";
import { ApiRequestError, enrollWorker } from "../api.ts";

type Enrollment = { code: string; expiresAt: string; installer: string };
export function EnrollmentWizard({ onCreated }: { onCreated: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null); const [audience, setAudience] = useState("linux-x64"); const [vcpu, setVcpu] = useState(4); const [memory, setMemory] = useState(8); const [storage, setStorage] = useState(80); const [result, setResult] = useState<Enrollment | null>(null); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  function open() { setResult(null); setError(null); dialog.current?.showModal(); }
  function close() { dialog.current?.close(); if (result) onCreated(); }
  async function create(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(null); try { setResult(await enrollWorker(audience, { vcpu, memoryBytes: memory * 1024 ** 3, storageBytes: storage * 1024 ** 3 })); } catch (reason) { setError(reason instanceof ApiRequestError ? reason.message : "Enrollment could not be created."); } finally { setPending(false); } }
  const commands = result ? `curl --fail --proto '=https' --tlsv1.3 ${result.installer} | sh` : "";
  return <><Button label="Enroll worker" variant="primary" clickAction={open} /><dialog ref={dialog} className="enrollment-dialog" onCancel={() => dialog.current?.close()} aria-labelledby="enrollment-title"><div className="panel-kicker">Worker enrollment</div><h2 id="enrollment-title">Bring an appliance online</h2>{!result ? <form onSubmit={(event) => void create(event)}><p className="muted">Create a one-use enrollment for a worker. The code expires after 15 minutes and is never included in the installer command.</p><label>Platform<select value={audience} onChange={(event) => setAudience(event.target.value)}><option value="linux-x64">Linux x64 · Kata appliance</option><option value="windows-x64">Windows x64 · Hyper-V appliance</option><option value="macos-arm64">macOS arm64 · Tart worker</option></select></label><div className="field-row"><label>vCPU<input type="number" min="1" value={vcpu} onChange={(event) => setVcpu(Number(event.target.value))} /></label><label>Memory (GiB)<input type="number" min="1" value={memory} onChange={(event) => setMemory(Number(event.target.value))} /></label><label>Storage (GiB)<input type="number" min="1" value={storage} onChange={(event) => setStorage(Number(event.target.value))} /></label></div>{error && <p className="inline-error" role="alert">{error}</p>}<div className="dialog-actions"><Button label="Cancel" variant="secondary" type="button" onClick={() => dialog.current?.close()} /><Button label="Generate enrollment" variant="primary" type="submit" isLoading={pending} /></div></form> : <div className="enrollment-result"><p className="warning-note"><strong>Copy this code now.</strong> It is shown once, expires {new Date(result.expiresAt).toLocaleTimeString()}, and cannot be recovered.</p><label htmlFor="enrollment-code">One-use enrollment code</label><div className="copy-block"><code id="enrollment-code" tabIndex={0}>{result.code}</code><Button label="Copy code" variant="secondary" clickAction={() => void navigator.clipboard?.writeText(result.code)} /></div><label htmlFor="installer-command">Installer commands</label><pre id="installer-command" className="command-block" tabIndex={0}>{commands}</pre><p className="muted">Paste the code only when the signed installer asks through its hidden prompt. Never put it in a URL, argument, or environment variable.</p><div className="dialog-actions"><Button label="Done" variant="primary" onClick={close} /></div></div>}</dialog></>;
}
