import type { WorkerDoctor as WorkerDoctorDto } from "@whitesmith/contracts";

const checks: Array<[keyof Pick<WorkerDoctorDto, "nestedKvm" | "kvmModules" | "probe" | "egress" | "imageSignatures" | "blockVolume">, string]> = [["nestedKvm", "Nested KVM"], ["kvmModules", "KVM and vhost modules"], ["probe", "Disposable Kata probe"], ["egress", "Public egress"], ["imageSignatures", "Image signatures"], ["blockVolume", "Block volume support"]];
export function WorkerDoctor({ doctor }: { doctor: WorkerDoctorDto | null }) {
  if (!doctor) return <section className="doctor-panel"><div className="panel-kicker">Runtime doctor</div><p className="muted">No doctor report yet. Save limits after adoption to enable dispatch.</p></section>;
  const failedChecks = checks.filter(([key]) => doctor[key] === false).length;
  const handlerFailed = doctor.runtimeHandler !== undefined && doctor.runtimeHandler !== "kata-qemu-runtime-rs";
  const failed = failedChecks + (handlerFailed ? 1 : 0);
  return <section className="doctor-panel" aria-labelledby="doctor-title"><div className="panel-heading"><div><div className="panel-kicker">Runtime doctor</div><h3 id="doctor-title">{failed ? "Remediation required" : "Ready for dispatch"}</h3></div><span className={`status-pill ${failed ? "status-bad" : "status-good"}`}>{failed ? `${failed} checks need attention` : "Observed checks pass"}</span></div><ul className="doctor-checks">{checks.map(([key, label]) => { const known = typeof doctor[key] === "boolean"; const passed = doctor[key] === true; return <li key={key} className={known ? (passed ? "check-pass" : "check-fail") : "check-unknown"}><span aria-hidden="true">{known ? (passed ? "✓" : "×") : "?"}</span><span>{label}</span><strong>{known ? (passed ? "Pass" : "Fix") : "Unknown"}</strong></li>; })}<li className={doctor.runtimeHandler === undefined ? "check-unknown" : (handlerFailed ? "check-fail" : "check-pass")}><span aria-hidden="true">{doctor.runtimeHandler === undefined ? "?" : (handlerFailed ? "×" : "✓")}</span><span>Runtime handler</span><strong>{doctor.runtimeHandler === undefined ? "Unknown" : (handlerFailed ? "Fix" : "Pass")}</strong></li></ul></section>;
}
