import { useMemo, useState, type FormEvent } from "react";
import { useMutation } from "@tanstack/react-query";
import type { WorkerCapacityData, WorkerLimits } from "@whitesmith/contracts";
import { configurePendingWorker, configureWorker, rejectPendingWorker, type WorkerConfigurationInput } from "../api.ts";
type Props = { worker: { id: string; platform?: "linux-x64" | "windows-x64" | "macos-arm64"; guestPlatforms?: ("linux-x64" | "windows-x64" | "macos-arm64")[]; draining?: boolean; activeSandboxes?: number; capacity: WorkerCapacityData; limits: WorkerLimits | null }; organizationId?: string; onConfigured(): void; onDiscard?(): void };
const GIB = 1024 ** 3;
const initialGiB = (bytes: number) => { const value = Math.floor(bytes / GIB); return value > 0 ? String(value) : ""; };
const parsePositiveInteger = (value: string) => { if (!/^\d+$/.test(value)) return null; const parsed = Number(value); return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : null; };
const toBytes = (value: string) => { const gib = parsePositiveInteger(value); if (gib === null || gib > Math.floor(Number.MAX_SAFE_INTEGER / GIB)) return null; const bytes = gib * GIB; return Number.isSafeInteger(bytes) ? bytes : null; };
export function WorkerConfigurationForm({ worker, organizationId, onConfigured, onDiscard }: Props) {
  const c = worker.capacity;
  const discard = useMutation({ mutationFn: rejectPendingWorker, onSuccess: () => onDiscard?.() });
  const platform = worker.platform ?? "linux-x64";
  const canEditGuests = !organizationId || (worker.draining === true && worker.activeSandboxes === 0);
  const [allowLinux, setAllowLinux] = useState(() => worker.guestPlatforms?.includes("linux-x64") ?? false);
  const [vcpu, setVcpu] = useState(String(c.freeVcpu));
  const [ram, setRam] = useState(initialGiB(c.freeMemoryBytes));
  const [disk, setDisk] = useState(initialGiB(c.freeStorageBytes));
  const [maxVcpu, setMaxVcpu] = useState(() => String(Math.max(1, Math.floor(c.freeVcpu / 2))));
  const [maxRam, setMaxRam] = useState(() => initialGiB(Math.floor(c.freeMemoryBytes / 2)));
  const [maxDisk, setMaxDisk] = useState(() => initialGiB(Math.floor(c.freeStorageBytes / 2)));
  const [concurrency, setConcurrency] = useState("1");
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const capacityError = useMemo(() => c.freeMemoryBytes < GIB || c.freeStorageBytes < GIB ? "This worker reports less than 1 GiB of free RAM or disk; increase its capacity before configuring it." : null, [c.freeMemoryBytes, c.freeStorageBytes]);
  const capabilityHelp = platform === "windows-x64" ? <div><label className="checkbox-field"><input type="checkbox" name="allowLinux" checked={allowLinux} disabled={!canEditGuests || pending} onChange={(event) => setAllowLinux(event.target.checked)} /> Allow Linux VMs</label>{organizationId && !canEditGuests && <p className="field-help">Drain this worker and wait for active jobs to finish before changing guest operating systems.</p>}</div> : null;
  const submit = (event: FormEvent) => {
    event.preventDefault();
    const applianceVcpu = parsePositiveInteger(vcpu), applianceMemory = toBytes(ram), applianceStorage = toBytes(disk), podVcpu = parsePositiveInteger(maxVcpu), podMemory = toBytes(maxRam), podStorage = toBytes(maxDisk), maxConcurrentPods = parsePositiveInteger(concurrency);
    if (!applianceVcpu || !applianceMemory || !applianceStorage || !podVcpu || !podMemory || !podStorage || !maxConcurrentPods) return setError("All resource values must be positive whole numbers.");
    if (applianceVcpu > c.freeVcpu || applianceMemory > c.freeMemoryBytes || applianceStorage > c.freeStorageBytes) return setError("Appliance resources cannot exceed the worker's reported free capacity.");
    if (podVcpu > applianceVcpu || podMemory > applianceMemory || podStorage > applianceStorage) return setError("Per-job ceilings cannot exceed appliance resources.");
    if (podVcpu * maxConcurrentPods > applianceVcpu || podMemory * maxConcurrentPods > applianceMemory || podStorage * maxConcurrentPods > applianceStorage) return setError("Per-job ceilings multiplied by concurrency cannot exceed appliance resources.");
    const guestPlatforms: WorkerConfigurationInput["guestPlatforms"] = platform === "windows-x64" ? (allowLinux ? ["windows-x64", "linux-x64"] : ["windows-x64"]) : [platform];
    const input: WorkerConfigurationInput = { appliance: { vcpu: applianceVcpu, memoryBytes: applianceMemory, storageBytes: applianceStorage }, runtime: { maxVcpuPerPod: podVcpu, maxMemoryBytesPerPod: podMemory, maxStorageBytesPerPod: podStorage, maxConcurrentPods }, guestPlatforms };
    setError(null); setPending(true);
    void (organizationId ? configureWorker(organizationId, worker.id, input) : configurePendingWorker(worker.id, input)).then(onConfigured).catch((reason) => setError(reason instanceof Error ? reason.message : "Worker configuration failed.")).finally(() => setPending(false));
  };
  return <><div className="worker-configuration-actions"><button type="button" className="control-button" onClick={() => { if (window.confirm("Discard this pending worker and generate a new installation?")) discard.mutate(worker.id); }} disabled={discard.isPending}>Discard and reinstall</button></div><form className="worker-configuration-form" onSubmit={submit}><header className="worker-configuration-header"><div><p className="eyebrow">Approval and capacity</p><h3>Approve and configure worker</h3><p>Review the worker's reported capacity, then apply the limits it may use. Approval and configuration happen together.</p></div><span className="worker-status-badge">Pending approval</span></header>{capacityError && <p role="alert" className="form-error">{capacityError}</p>}{error && <p role="alert" className="form-error">{error}</p>}{capabilityHelp}<fieldset><legend>Worker capacity</legend><p className="field-help">Reported free capacity: {c.freeVcpu} vCPU · {initialGiB(c.freeMemoryBytes)} GiB RAM · {initialGiB(c.freeStorageBytes)} GiB disk</p><div className="limit-grid"><label>vCPU<input name="vcpu" type="number" min="1" max={c.freeVcpu} step="1" value={vcpu} onChange={(e) => setVcpu(e.target.value)} required /><small>Maximum appliance allocation</small></label><label>RAM (GiB)<input name="memoryGiB" type="number" min="1" max={initialGiB(c.freeMemoryBytes)} step="1" value={ram} onChange={(e) => setRam(e.target.value)} required /><small>Maximum appliance allocation</small></label><label>Disk (GiB)<input name="storageGiB" type="number" min="1" max={initialGiB(c.freeStorageBytes)} step="1" value={disk} onChange={(e) => setDisk(e.target.value)} required /><small>Maximum appliance allocation</small></label></div></fieldset><fieldset><legend>Per-job limits</legend><p className="field-help">Each job is isolated. Limits are multiplied by concurrency and must fit within the worker capacity above.</p><div className="limit-grid"><label>Max vCPU per job<input name="maxVcpuPerPod" type="number" min="1" step="1" value={maxVcpu} onChange={(e) => setMaxVcpu(e.target.value)} required /></label><label>Max RAM per job (GiB)<input name="maxMemoryGiBPerPod" type="number" min="1" step="1" value={maxRam} onChange={(e) => setMaxRam(e.target.value)} required /></label><label>Max disk per job (GiB)<input name="maxStorageGiBPerPod" type="number" min="1" step="1" value={maxDisk} onChange={(e) => setMaxDisk(e.target.value)} required /></label><label>Max concurrent jobs<input name="maxConcurrentPods" type="number" min="1" step="1" value={concurrency} onChange={(e) => setConcurrency(e.target.value)} required /></label></div></fieldset><div className="worker-configuration-actions"><button className="control-button" type="submit" disabled={pending || Boolean(capacityError)}>{pending ? "Approving and configuring…" : "Approve and configure worker"}</button></div></form></>;
}
