import { Hono } from "hono";
import type { Context } from "hono";
import type { ControlPlaneEnv, ControlPlaneHttpDeps } from "./types.ts";
import { createEnrollmentCode, consumeJoin, fingerprint, adoptWorker } from "../workers.ts";
export function registerWorkerRoutes(app: Hono<ControlPlaneEnv>, deps: ControlPlaneHttpDeps) {
  const auth = async (c: Context<ControlPlaneEnv>) => deps.currentUser(c.req.raw);
  app.get("/api/workers/installer", async (c) => { const audience = c.req.query("audience"); const file = audience === "linux-x64" ? "install-worker.sh" : audience === "windows-x64" ? "install-worker.ps1" : audience === "macos-arm64" ? "install-worker-macos.sh" : null; if (!file) return c.json({ error: "unsupported installer audience" }, 400); return new Response(Bun.file(new URL(file, deps.workerInstallerRoot)), { headers: { "cache-control": "no-store" } }); });
  app.post("/api/workers/join", async (c) => { const body = await c.req.json<{code:string;publicKey:string;platform:string;vmUuid:string;limits:Record<string,number>}>(); if (!await consumeJoin(deps.db, Buffer.from(body.code, "base64url"))) return c.json({ error: "invalid or expired join" }, 401); const [worker] = await deps.db`insert into workers (name,platform,admission_state,public_key,fingerprint,vm_uuid,limits) values (${body.vmUuid},${body.platform},'pending',${body.publicKey},${fingerprint(body.publicKey)},${body.vmUuid},${JSON.stringify(body.limits)}) returning id,fingerprint`; return c.json({ workerId: worker.id, fingerprint: worker.fingerprint }, 201); });
  app.get("/api/workers", async (c) => { const user = await auth(c); if (!user) return c.json({ code: "unauthorized", message: "Authentication required", requestId: deps.requestId() }, 401); return c.json(await deps.db`select id,name,platform,admission_state as "admissionState",connection_state as "connectionState",configuration_state as "configurationState",fingerprint,limits,doctor from workers order by created_at desc`); });
  app.post("/api/workers/enroll", async (c) => { const user = await auth(c); if (!user) return c.json({ code: "unauthorized", message: "Authentication required", requestId: deps.requestId() }, 401); if (!user.isGlobalAdmin) return c.json({ error: "forbidden" }, 403); const body = await c.req.json<{audience:string;profile:Record<string,number>}>(); const e = createEnrollmentCode(); await deps.db`insert into worker_join_codes (guest_token_hash,status_token_hash,audience,requested_profile,canonical_base_url,expires_at) values (${e.guestHash},${e.statusHash},${body.audience},${JSON.stringify(body.profile)},${deps.baseUrl},${e.expiresAt})`; return c.json({ code: e.code, expiresAt: e.expiresAt.toISOString() }, 201); });
  app.post("/api/workers/:workerId/adopt", async (c) => { const user = await auth(c); if (!user) return c.json({ code: "unauthorized", message: "Authentication required", requestId: deps.requestId() }, 401); if (!user.isGlobalAdmin) return c.json({ error: "forbidden" }, 403); await adoptWorker(deps.db, c.req.param("workerId"), user.id); deps.onWorkerAdopted(c.req.param("workerId")); return c.json({ ok: true }); });
}
