import { useNavigate, useSearch } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import type { CostCenterBreakdown, CostCenterDto, CostCenterExternalBreakdown, CostCenterPricingProvider, DashboardPeriod } from "@mars/contracts";
import { getCostCenter } from "../api.ts";
import { QueryState } from "../components/StateView.tsx";
import { ReportingPeriodControl, reportingPeriodLabels } from "../components/ReportingPeriodControl.tsx";
import { GithubRunnerCostDisclosure } from "../components/GithubRunnerCostDisclosure.tsx";
import { useOrganizationFromRoute } from "./useOrganization.ts";
import { formatMinutes, formatUsdMicros } from "../format.ts";
import { CostCenterPriceChart } from "../components/CostCenterPriceChart.tsx";

const providerLabels: Record<CostCenterPricingProvider, string> = { github: "GitHub-hosted", blacksmith: "Blacksmith", "azure-vm": "Azure VM" };
export const costCenterQueryOptions = (organizationId: string, period: DashboardPeriod, provider: CostCenterPricingProvider = "github") => ({ queryKey: ["org", organizationId, "cost-center", period, provider], queryFn: () => getCostCenter(organizationId, period, provider), enabled: Boolean(organizationId), ...(organizationId === "all" ? { refetchInterval: 5_000 } : {}) });
export const formatPlatform = (platform: string) => ({ "linux-x64": "Linux x64", "linux-arm64": "Linux ARM64 (Docker Desktop)", "windows-x64": "Windows x64", "macos-arm64": "macOS arm64" } as Record<string, string>)[platform] ?? platform;
export const formatRunner = (row: Pick<CostCenterBreakdown, "githubRunnerSku" | "githubRunnerVcpu">, provider: CostCenterPricingProvider = "github") => row.githubRunnerSku && row.githubRunnerVcpu ? `${row.githubRunnerSku} · ${row.githubRunnerVcpu} vCPU` : `No comparable ${providerLabels[provider]} runner`;
export const formatMinutesBreakdown = (row: CostCenterBreakdown) => row.unpricedMinutes > 0 ? `${formatMinutes(row.pricedMinutes)} priced · ${formatMinutes(row.unpricedMinutes)} unmatched` : formatMinutes(row.selfHostedMinutes);

function PageHeader({ period, provider, onPeriodChange, onProviderChange }: { period: DashboardPeriod; provider: CostCenterPricingProvider; onPeriodChange: (period: DashboardPeriod) => void; onProviderChange: (provider: CostCenterPricingProvider) => void }) {
  return <header className="page-header cost-center-header"><div><p className="eyebrow">Cost Center / {reportingPeriodLabels[period]}</p><h1>Where the estimate comes from.</h1><p className="page-description">Completed Mars jobs and detected external GitHub Actions jobs, priced against equivalent {providerLabels[provider]} rates.</p></div><div><ReportingPeriodControl value={period} onChange={onPeriodChange} label="Cost Center time window" /><label>Compare pricing <select aria-label="Cost Center pricing provider" value={provider} onChange={(event) => onProviderChange(event.target.value as CostCenterPricingProvider)}><option value="github">GitHub</option><option value="blacksmith">Blacksmith</option><option value="azure-vm">Azure VM</option></select></label></div></header>;
}
export function Summary({ costSavings, externalCostMicros, externalMinutes, provider = "github" }: { costSavings: CostCenterDto["costSavings"]; externalCostMicros?: number; externalMinutes?: number; provider?: CostCenterPricingProvider }) {
  return <section className="cost-center-summary" aria-label="Cost Center summary"><div className="metric"><span>Estimated {providerLabels[provider]} retail cost avoided</span><strong>{formatUsdMicros(costSavings.estimatedSavingsMicros)}</strong><small>avoided retail compute estimate</small></div><div className="metric"><span>Estimated external {providerLabels[provider]} cost</span><strong>{formatUsdMicros(externalCostMicros ?? 0)}</strong><small>{formatMinutes(externalMinutes ?? 0)} detected external minutes</small></div><div className="metric"><span>Self-hosted billable-equivalent minutes</span><strong>{formatMinutes(costSavings.selfHostedMinutes)}</strong><small>all completed Mars jobs</small></div><div className="metric"><span>Priced Mars minutes</span><strong>{formatMinutes(costSavings.pricedMinutes)}</strong><small>matched to a dated runner rate</small></div></section>;
}
export function ExternalBreakdownTable({ rows, provider = "github" }: { rows: CostCenterExternalBreakdown[]; provider?: CostCenterPricingProvider }) {
  return <div className="cost-center-table-wrap"><table className="cost-center-table"><caption className="sr-only">Detected external GitHub Actions cost breakdown</caption><thead><tr><th scope="col">Repository</th><th scope="col">Detected runner</th><th scope="col">Jobs</th><th scope="col">Billable minutes</th><th scope="col">Estimated cost</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.organizationId}-${row.repositoryId}-${row.platform}-${row.requestedVcpu}-${row.githubRunnerSku ?? "unmatched"}`}><th scope="row">{row.repositoryName}</th><td>{formatPlatform(row.platform)} · {formatRunner(row, provider)}</td><td>{row.jobCount}</td><td>{formatMinutes(row.billableMinutes)}</td><td>{formatUsdMicros(row.estimatedCostMicros)}</td></tr>)}</tbody></table></div>;
}
export function BreakdownTable({ rows, provider = "github" }: { rows: CostCenterBreakdown[]; provider?: CostCenterPricingProvider }) {
  return <div className="cost-center-table-wrap"><table className="cost-center-table"><caption className="sr-only">Cost Center repository and comparable {provider === "github" ? "GitHub" : providerLabels[provider]} runner breakdown</caption><thead><tr><th scope="col">Repository</th><th scope="col">Mars request</th><th scope="col">Comparable {providerLabels[provider]} runner</th><th scope="col">Jobs</th><th scope="col">Billable minutes</th><th scope="col">Estimated savings</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.organizationId}-${row.repositoryId}-${row.platform}-${row.requestedVcpu}-${row.githubRunnerSku ?? "unmatched"}`}><th scope="row">{row.repositoryName}</th><td>{formatPlatform(row.platform)} · {row.requestedVcpu} vCPU</td><td>{formatRunner(row, provider)}</td><td>{row.jobCount}</td><td>{formatMinutesBreakdown(row)}</td><td>{formatUsdMicros(row.estimatedSavingsMicros)}</td></tr>)}</tbody></table></div>;
}
export function CostCenterPage() {
  const { organizationId } = useOrganizationFromRoute(); const search = useSearch({ from: "/_authenticated/cost-center" }); const navigate = useNavigate({ from: "/_authenticated/cost-center" });
  const period = search.period as DashboardPeriod, provider = search.provider as CostCenterPricingProvider; const query = useQuery(costCenterQueryOptions(organizationId, period, provider));
  const setSearch = (next: Partial<typeof search>) => void navigate({ to: "/cost-center", search: { ...search, ...next }, replace: true });
  return <><PageHeader period={period} provider={provider} onPeriodChange={(next) => setSearch({ period: next })} onProviderChange={(next) => setSearch({ provider: next })} /><QueryState error={query.error} isLoading={query.isLoading} retry={() => void query.refetch()} operationLabel="Cost Center" />{query.data && <><Summary costSavings={query.data.costSavings} externalCostMicros={query.data.estimatedExternalCostMicros} externalMinutes={query.data.externalMinutes} provider={provider} /><GithubRunnerCostDisclosure costSavings={query.data.costSavings} provider={provider} /><section className="cost-center-price-panel" aria-labelledby="cost-center-price-title"><div className="panel-kicker">Price over time</div><h2 id="cost-center-price-title">Estimated retail cost avoided by completion date</h2><CostCenterPriceChart points={query.data.priceOverTime} provider={provider} /></section>{query.data.breakdown.length > 0 ? <BreakdownTable rows={query.data.breakdown} provider={provider} /> : <p className="cost-center-empty">No completed Mars jobs were recorded in this period.</p>}<section aria-labelledby="external-cost-title"><div className="panel-kicker">External actions</div><h2 id="external-cost-title">Detected jobs outside Mars</h2>{query.data.externalBreakdown.length > 0 ? <ExternalBreakdownTable rows={query.data.externalBreakdown} provider={provider} /> : <p className="cost-center-empty">No detectable external GitHub-hosted jobs were recorded in this period.</p>}</section></>}</>;
}
