import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { approveOnboardingRepositories, beginOnboardingGithubInstall, beginOnboardingGithubManifest, createOnboardingPool, getOnboardingDetail, getOnboardingStatus, getPendingWorkerRequests, selectOnboardingWorker } from "../api.ts";
import { EnrollmentWizard } from "../components/EnrollmentWizard.tsx";
import { WorkerConfigurationForm } from "../components/WorkerConfigurationForm.tsx";
import type { CreatePoolRequest, OnboardingDetail, OnboardingStatus } from "@whitesmith/contracts";

const steps = [["admin", "Admin"], ["worker", "Worker"], ["github", "GitHub"], ["resources", "Resources"], ["labels", "Trigger labels"]] as const;
const gib = (bytes: number) => Math.max(1, Math.round(bytes / 1024 ** 3));

export function OnboardingPage() {
  const client = useQueryClient();
  const status = useQuery({ queryKey: ["onboarding-status"], queryFn: getOnboardingStatus, staleTime: 1000 });
  const s = status.data as OnboardingStatus | undefined;
  const detail = useQuery({ queryKey: ["onboarding"], queryFn: getOnboardingDetail, enabled: Boolean(s?.authenticated && s.canManage), refetchInterval: s?.step === "worker" || s?.step === "resources" ? 2000 : false });
  const [error, setError] = useState<string | null>(null);
  const [reviewIndex, setReviewIndex] = useState<number | null>(null);
  const refresh = () => { void client.invalidateQueries({ queryKey: ["onboarding"] }); void client.invalidateQueries({ queryKey: ["onboarding-status"] }); };
  const select = useMutation({ mutationFn: selectOnboardingWorker, onSuccess: () => { setReviewIndex(null); refresh(); }, onError: (e) => setError(e instanceof Error ? e.message : "Worker selection failed") });
  const approve = useMutation({ mutationFn: approveOnboardingRepositories, onSuccess: () => { setReviewIndex(null); refresh(); }, onError: (e) => setError(e instanceof Error ? e.message : "Repository approval failed") });
  const pool = useMutation({ mutationFn: createOnboardingPool, onSuccess: () => { setReviewIndex(null); refresh(); }, onError: (e) => setError(e instanceof Error ? e.message : "Pool creation failed") });
  if (status.isLoading) return <main className="onboarding"><p>Loading onboarding…</p></main>;
  if (status.error || !s) return <main className="onboarding"><h1>Onboarding unavailable</h1><p role="alert">{status.error instanceof Error ? status.error.message : "Could not load onboarding."}</p><button onClick={() => void status.refetch()}>Retry</button></main>;
  if (!s.authenticated) return <SignIn firstAdmin={!s.adminCreated} />;
  if (!s.canManage) return <main className="onboarding"><section className="onboarding-card"><h1>Administrator access required</h1><p>Your GitHub account is signed in, but it cannot configure this control plane.</p></section></main>;
  const d = detail.data;
  if (!d) return <main className="onboarding"><p>Loading setup details…</p></main>;
  if (d.step === "complete") return <Complete detail={d} />;
  const currentIndex = steps.findIndex(([id]) => id === d.step);
  return <main className="onboarding"><header><p className="eyebrow">FIRST-RUN SETUP</p><h1>Get Whitesmith ready</h1><p>Complete each verified step. Progress is saved on the control plane.</p></header>{error && <p role="alert" className="form-error">{error} <button onClick={() => setError(null)}>Dismiss</button></p>}<div className="onboarding-layout"><nav aria-label="Onboarding steps"><ol className="onboarding-steps">{steps.map(([id, label], index) => <li key={id} role={index < currentIndex ? "button" : undefined} tabIndex={index <= currentIndex ? 0 : -1} onClick={() => index < currentIndex && setReviewIndex(index)} onKeyDown={(e) => { if (index < currentIndex && (e.key === "Enter" || e.key === " ")) { e.preventDefault(); setReviewIndex(index); } }} className={index === currentIndex ? "is-current" : index < currentIndex ? "is-complete" : "is-locked"}><span>{index + 1}</span><strong>{label}</strong></li>)}</ol></nav><section className="onboarding-task" aria-live="polite"><h2>{reviewIndex !== null ? `${steps[reviewIndex]?.[1]} review` : steps[currentIndex]?.[1]}</h2>{reviewIndex !== null ? <ReviewSummary detail={d} through={reviewIndex + 1} onClose={() => setReviewIndex(null)} /> : <>{currentIndex > 0 && <ReviewSummary detail={d} through={currentIndex} />}{d.step === "worker" && <WorkerStep onSelect={(id) => select.mutate({ workerId: id })} />}{d.step === "github" && <GithubStep detail={d} onApprove={(ids) => approve.mutate({ repositoryIds: ids })} />}{d.step === "resources" && <ResourceStep detail={d} onDone={refresh} />}{d.step === "labels" && <LabelsStep detail={d} onCreate={(input) => pool.mutate({ ...input, organizationId: d.github.organizationId ?? "" })} />}</>}</section></div></main>;
}

function SignIn({ firstAdmin }: { firstAdmin: boolean }) { return <main className="onboarding"><section className="onboarding-card onboarding-sign-in"><p className="eyebrow">{firstAdmin ? "WELCOME TO WHITESMITH" : "WELCOME BACK"}</p><h1>{firstAdmin ? "Create your administrator account" : "Sign in to Whitesmith"}</h1><p>Use GitHub to verify your identity and securely manage this control plane.</p><a className="button" href="/api/auth/github">{firstAdmin ? "Continue with GitHub" : "Continue with GitHub"}</a><p>{firstAdmin ? "Create administrator with GitHub" : "Sign in with GitHub"}</p><p><strong>GitHub identity</strong><br />Only your GitHub identity is used for administrator access.</p><p className="security-note">Security note: setup data is shown only after your session is authorized.</p></section></main>; }
function ReviewSummary({ detail, through, onClose }: { detail: OnboardingDetail; through: number; onClose?: () => void }) { const org = detail.organizations.find((item) => item.id === detail.github.organizationId); return <aside className="onboarding-review">{onClose && <button type="button" onClick={onClose}>Back to current step</button>}<h3>Completed setup</h3>{through >= 1 && <p>Worker enrollment · Use this worker<br />Worker: {detail.worker?.name ?? detail.worker?.vmUuid ?? "Selected"}</p>}{through >= 2 && <p>GitHub organization: {org?.name ?? detail.github.organizationId ?? "Connected"}<br />Repositories: {detail.github.repositories.filter((r) => r.approved).map((r) => r.name).join(", ") || "Pending approval"}</p>}</aside>; }
function WorkerStep({ onSelect }: { onSelect: (id: string) => void }) { const q = useQuery({ queryKey: ["pending-workers"], queryFn: getPendingWorkerRequests, refetchInterval: 2000 }); return <div><EnrollmentWizard onCreated={() => void q.refetch()} showRotation={false} /><p>Choose the worker you verified. It remains unschedulable until resources are configured.</p>{q.error && <p role="alert">Could not load workers.</p>}{(q.data ?? []).map((w) => <article className="worker-choice" key={w.id}><h3>{w.vmUuid}</h3><p>{w.platform} · {w.fingerprint}</p><p>{w.capacity.freeVcpu} vCPU · {gib(w.capacity.freeMemoryBytes)} GiB RAM · {gib(w.capacity.freeStorageBytes)} GiB disk</p><button type="button" onClick={() => onSelect(w.id)}>Use this worker</button></article>)}{q.data?.length === 0 && <p>No pending worker requests yet.</p>}</div>; }
function GithubStep({ detail, onApprove }: { detail: OnboardingDetail; onApprove: (ids: string[]) => void }) { const [selected, setSelected] = useState<string[]>([]); const [organizationId, setOrganizationId] = useState(detail.github.organizationId ?? ""); const repos = detail.github.repositories.filter((r) => r.available && (r.visibility === "private" || r.visibility === "internal")); const selectionRemediation = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("github") === "repository-selection-required"; const connect = async () => { if (!organizationId) return; if (detail.github.appConfigured) { const result = await beginOnboardingGithubInstall({ organizationId }); window.location.assign(result.location); } else { const result = await beginOnboardingGithubManifest({ organizationId }); const form = document.createElement("form"); form.method = "post"; form.action = result.action; const manifest = document.createElement("input"); manifest.type = "hidden"; manifest.name = "manifest"; manifest.value = result.manifest; form.appendChild(manifest); document.body.appendChild(form); form.submit(); } }; return <div><h3>GitHub organization</h3>{selectionRemediation && <p role="alert">GitHub did not grant a usable private or internal repository. Click Connect organization, choose <strong>Only select repositories</strong>, and select at least one private or internal repository.</p>}{!detail.github.organizationId && <><p>Select the GitHub organization to connect.</p><select aria-label="GitHub organization" value={organizationId} onChange={(e) => setOrganizationId(e.target.value)}><option value="">Choose an organization</option>{detail.organizations.map((org) => <option key={org.id} value={org.id}>{org.name}</option>)}</select><button type="button" onClick={() => void connect()} disabled={!organizationId}>{detail.github.appConfigured ? "Connect organization" : "Register GitHub App"}</button></>}{detail.github.organizationId && <p>Select available private or internal repositories granted to the GitHub App.</p>}{detail.github.organizationId && repos.length === 0 && <button type="button" onClick={() => void connect()}>Connect organization</button>}{repos.map((r) => <label key={r.id} className="checkbox-row"><input type="checkbox" name={r.id} checked={selected.includes(r.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, r.id] : selected.filter((id) => id !== r.id))} /> {r.name}</label>)}{repos.length > 0 && <button type="button" onClick={() => onApprove(selected)} disabled={selected.length === 0}>Approve repositories</button>}</div>; }
function ResourceStep({ detail, onDone }: { detail: OnboardingDetail; onDone: () => void }) { const w = detail.worker; if (!w) return <p>Select a worker first.</p>; return <><h3>Configure resources</h3>{w.configurationState === "ready" ? <p role="status">Configuring worker complete. Waiting for server progress…</p> : <WorkerConfigurationForm worker={w} organizationId={detail.github.organizationId ?? ""} onConfigured={onDone} />}</>; }
function LabelsStep({ detail, onCreate }: { detail: OnboardingDetail; onCreate: (input: CreatePoolRequest) => void }) { const [name, setName] = useState("default"); const [label, setLabel] = useState("whitesmith-default"); const worker = detail.worker; const digest = detail.defaultImageDigest; const platformLabels = worker?.platform === "linux-x64" ? ["self-hosted", "linux", "x64"] : worker?.platform === "windows-x64" ? ["self-hosted", "windows", "x64"] : ["self-hosted", "macos", "arm64"]; if (!worker || !digest) return <p role="alert">No signed default job image is configured for {worker?.platform ?? "the selected platform"}.</p>; if (!worker.limits) return <div><p role="alert">Worker resource limits are not acknowledged yet. Return to Configure resources before creating a pool.</p><p>Configuring worker · resources in GiB</p><p>Trigger label: {label}</p><pre>runs-on: [{[...platformLabels, label].join(", ")}]</pre></div>; const resources = { vcpu: worker.limits.maxVcpuPerPod, memoryBytes: worker.limits.maxMemoryBytesPerPod, storageBytes: worker.limits.maxStorageBytesPerPod, concurrency: worker.limits.maxConcurrentPods }; return <form onSubmit={(e) => { e.preventDefault(); onCreate({ workerId: worker.id, name, triggerLabel: label, imageDigest: digest, resources }); }}><p>Configuring worker acknowledged. Resources are acknowledged; configure resources in GiB before creating the first enabled pool.</p><label>Pool name<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Trigger label<input value={label} onChange={(e) => setLabel(e.target.value)} pattern="[a-z0-9][a-z0-9._-]{0,62}" /></label><p>Effective labels: <code>{[...platformLabels, label].join(", ")}</code></p><pre>runs-on: [{[...platformLabels, label].join(", ")}]</pre><button type="submit">Create pool</button></form>; }
function Complete({ detail }: { detail: OnboardingDetail }) { const org = detail.organizations.find((o) => o.id === detail.github.organizationId); return <main className="onboarding"><section className="onboarding-card"><h1>Onboarding complete</h1><p>Organization: {org?.name ?? detail.github.organizationId}</p><p>Approved repositories: {detail.github.repositories.filter((r) => r.approved).length}</p><p>Worker: {detail.worker?.name ?? "Ready"}</p><p>Pool: {detail.pool?.name ?? "default"}</p><p>Effective labels: {detail.pool?.labels?.join(", ")}</p><pre>runs-on: [{detail.pool?.labels?.join(", ")}]</pre><a className="button" href="/">Open dashboard</a></section></main>; }
