import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { approveOnboardingRepositories, beginOnboardingGithubInstall, beginOnboardingGithubManifest, createOnboardingPool, getOnboardingDetail, getOnboardingStatus, selectOnboardingWorker } from "../api.ts";
import { EnrollmentPanel } from "../components/EnrollmentPanel.tsx";
import { pendingWorkerQueryOptions } from "../components/PendingWorkerRequests.tsx";
import { RunnerWorkflowPrModal } from "../components/RunnerWorkflowPrModal.tsx";
import { WorkerConfigurationForm } from "../components/WorkerConfigurationForm.tsx";
import type { CreatePoolRequest, OnboardingDetail, OnboardingStatus } from "@whitesmith/contracts";

const steps = [["admin", "Admin"], ["worker", "Worker"], ["github", "GitHub"], ["resources", "Resources"], ["labels", "Trigger labels"]] as const;
const gib = (bytes: number) => Math.max(1, Math.round(bytes / 1024 ** 3));

export function OnboardingPage() {
  const client = useQueryClient();
  const status = useQuery({ queryKey: ["onboarding-status"], queryFn: getOnboardingStatus, staleTime: 1000 });
  const s = status.data as OnboardingStatus | undefined;
  const detail = useQuery({ queryKey: ["onboarding"], queryFn: getOnboardingDetail, enabled: Boolean(s?.authenticated && s.canManage), refetchInterval: s?.step === "worker" || s?.step === "resources" ? 2000 : false });
  const [error, setError] = useState<string | null>(null);
  const [reviewIndex, setReviewIndex] = useState<number | null>(null);
  const refresh = () => { void client.invalidateQueries({ queryKey: ["onboarding"] }); void client.invalidateQueries({ queryKey: ["onboarding-status"] }); };
  const select = useMutation({ mutationFn: selectOnboardingWorker, onSuccess: () => { setReviewIndex(null); refresh(); }, onError: (e) => setError(e instanceof Error ? e.message : "Worker selection failed") });
  const approve = useMutation({ mutationFn: approveOnboardingRepositories, onSuccess: () => { setReviewIndex(null); refresh(); }, onError: (e) => setError(e instanceof Error ? e.message : "Repository approval failed") });
  const pool = useMutation({ mutationFn: createOnboardingPool, onSuccess: () => { setReviewIndex(null); refresh(); }, onError: (e) => setError(e instanceof Error ? e.message : "Pool creation failed") });
  if (status.isLoading) return <main className="onboarding"><p>Loading onboarding…</p></main>;
  if (status.error || !s) return <main className="onboarding"><h1>Onboarding unavailable</h1><p role="alert">{status.error instanceof Error ? status.error.message : "Could not load onboarding."}</p><button onClick={() => void status.refetch()}>Retry</button></main>;
  if (!s.authenticated) return <SignIn firstAdmin={!s.adminCreated} />;
  if (!s.canManage) return <main className="onboarding"><section className="onboarding-card"><h1>Administrator access required</h1><p>Your GitHub account is signed in, but it cannot configure this control plane.</p></section></main>;
  const d = detail.data;
  if (detail.error) return <main className="onboarding"><h1>Onboarding unavailable</h1><p role="alert">{detail.error instanceof Error ? detail.error.message : "Could not load setup details."}</p><button type="button" onClick={() => void detail.refetch()}>Retry</button><a className="button" href="/api/auth/github">Sign in with GitHub</a></main>;
  if (!d) return <main className="onboarding"><p>Loading setup details…</p></main>;
  if (d.step === "complete") return <Complete detail={d} />;
  const currentIndex = steps.findIndex(([id]) => id === d.step);
  return <main className="onboarding"><header><p className="eyebrow">FIRST-RUN SETUP</p><h1>Get Whitesmith ready</h1><p>Complete each verified step. Progress is saved on the control plane.</p></header>{error && <p role="alert" className="form-error">{error} <button onClick={() => setError(null)}>Dismiss</button></p>}<div className="onboarding-layout"><nav aria-label="Onboarding steps"><ol className="onboarding-steps">{steps.map(([id, label], index) => <li key={id} role={index < currentIndex ? "button" : undefined} tabIndex={index <= currentIndex ? 0 : -1} onClick={() => index < currentIndex && setReviewIndex(index)} onKeyDown={(e) => { if (index < currentIndex && (e.key === "Enter" || e.key === " ")) { e.preventDefault(); setReviewIndex(index); } }} className={index === currentIndex ? "is-current" : index < currentIndex ? "is-complete" : "is-locked"}><span>{index + 1}</span><strong>{label}</strong></li>)}</ol></nav><section className="onboarding-task" aria-live="polite"><h2>{reviewIndex !== null ? `${steps[reviewIndex]?.[1]} review` : steps[currentIndex]?.[1]}</h2>{reviewIndex !== null ? <ReviewSummary detail={d} through={reviewIndex + 1} onClose={() => setReviewIndex(null)} /> : <>{currentIndex > 0 && <ReviewSummary detail={d} through={currentIndex} />}{d.step === "worker" && <WorkerStep onSelect={(id) => select.mutate({ workerId: id })} />}{d.step === "github" && <GithubStep detail={d} onApprove={(ids) => approve.mutate({ repositoryIds: ids })} />}{d.step === "resources" && <ResourceStep detail={d} onDone={refresh} />}{d.step === "labels" && <LabelsStep detail={d} onCreate={(input) => pool.mutate({ ...input, organizationId: d.github.organizationId ?? "" })} />}</>}</section></div></main>;
}

function SignIn({ firstAdmin }: { firstAdmin: boolean }) { return <main className="onboarding"><section className="onboarding-card onboarding-sign-in"><p className="eyebrow">{firstAdmin ? "WELCOME TO WHITESMITH" : "WELCOME BACK"}</p><h1>{firstAdmin ? "Create your administrator account" : "Sign in to Whitesmith"}</h1><p>Use GitHub to verify your identity and securely manage this control plane.</p><a className="button" href="/api/auth/github">{firstAdmin ? "Continue with GitHub" : "Continue with GitHub"}</a><p>{firstAdmin ? "Create administrator with GitHub" : "Sign in with GitHub"}</p><p><strong>GitHub identity</strong><br />Only your GitHub identity is used for administrator access.</p><p className="security-note">Security note: setup data is shown only after your session is authorized.</p></section></main>; }
function ReviewSummary({ detail, through, onClose }: { detail: OnboardingDetail; through: number; onClose?: () => void }) { const org = detail.organizations.find((item) => item.id === detail.github.organizationId); return <aside className="onboarding-review">{onClose && <button type="button" onClick={onClose}>Back to current step</button>}<h3>Completed setup</h3>{through >= 1 && detail.worker && <p>Worker enrollment<br />Worker: {detail.worker.name ?? detail.worker.vmUuid}</p>}{through >= 2 && <p>GitHub organization: {org?.name ?? detail.github.organizationId ?? "Connected"}<br />Repositories: {detail.github.repositories.filter((r) => r.approved).map((r) => r.name).join(", ") || "Pending approval"}</p>}</aside>; }
function WorkerStep({ onSelect }: { onSelect: (id: string) => void }) { const q = useQuery(pendingWorkerQueryOptions()); return <div><EnrollmentPanel workers={q.data ?? []} onConnected={() => void q.refetch()} showRotation={false} /><p>Choose the worker you verified. It remains unschedulable until resources are configured.</p>{q.error && <p role="alert">{q.error instanceof Error ? q.error.message : "Could not load workers."} <button type="button" onClick={() => void q.refetch()}>Retry</button></p>}{(q.data ?? []).map((w) => <article className="worker-choice" key={w.id}><h3>{w.vmUuid}</h3><p>{w.platform} · {w.connectionState}</p><p>Fingerprint: <code>{w.fingerprint}</code></p><button type="button" onClick={() => onSelect(w.id)}>Use this worker</button></article>)}</div>; }
function GithubStep({ detail, onApprove }: { detail: OnboardingDetail; onApprove: (ids: string[]) => void }) { const [selected, setSelected] = useState<string[]>([]); const [organizationId, setOrganizationId] = useState(detail.github.organizationId ?? ""); const repos = detail.github.repositories.filter((r) => r.available && r.visibility !== "public"); const allRepositories = detail.github.installation?.repositorySelection === "all"; const hasUsableInstallation = Boolean(detail.github.installation && repos.length > 0); const selectionRemediation = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("github") === "repository-selection-required"; const connect = async () => { if (!organizationId) return; try { const result = await beginOnboardingGithubInstall({ organizationId }); window.location.assign(result.location); } catch (cause) { /* surfaced by parent refresh */ } }; return <div><h3>Connect GitHub organization</h3>{!hasUsableInstallation && <><p>Choose an organization and install the Whitesmith GitHub App.</p><select aria-label="GitHub organization" value={organizationId} onChange={(e) => setOrganizationId(e.target.value)}><option value="">Select organization</option>{detail.organizations.map((o) => <option key={o.id} value={o.id}>{o.login}</option>)}</select><button type="button" onClick={() => void connect()}>{detail.github.appConfigured ? "Connect organization" : "Register GitHub App"}</button></>}{selectionRemediation && <p role="alert">The GitHub App is installed with all repositories. Reconnect and choose Only select repositories, then approve at least one available private or internal repository.</p>}{allRepositories && <p className="warning-note">This installation grants all repositories. You can still approve specific available repositories below.</p>}{hasUsableInstallation && <form onSubmit={(e) => { e.preventDefault(); if (selected.length) onApprove(selected); }}><p>Select the available private or internal repositories Whitesmith may schedule.</p>{repos.map((r) => <label key={r.id}><input type="checkbox" name={r.id} checked={selected.includes(r.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, r.id] : selected.filter((id) => id !== r.id))} />{r.name} ({r.visibility})</label>)}<button type="submit" disabled={!selected.length}>Approve repositories</button></form>}</div>; }
function ResourceStep({ detail, onDone }: { detail: OnboardingDetail; onDone: () => void }) { const w = detail.worker; if (!w) return <p>Select a worker first.</p>; return <><h3>Configure resources</h3>{w.configurationState === "ready" ? <p role="status">Configuring worker complete. Waiting for server progress…</p> : <WorkerConfigurationForm worker={w} onConfigured={onDone} />}</>; }
function LabelsStep({ detail, onCreate }: { detail: OnboardingDetail; onCreate: (input: CreatePoolRequest) => void }) { const [name, setName] = useState("default"); const [label, setLabel] = useState("whitesmith-default"); const [guestPlatform, setGuestPlatform] = useState<"linux-x64" | "windows-x64" | "macos-arm64" | null>(null); const worker = detail.worker; const guestPlatforms = worker?.guestPlatforms ?? (worker ? [worker.platform] : []); const selectedGuest = guestPlatform ?? guestPlatforms[0] ?? null; const digest = selectedGuest ? (detail.defaultImageDigests ?? {})[selectedGuest] ?? detail.defaultImageDigest ?? null : null; const platformLabels = selectedGuest === "linux-x64" ? ["self-hosted", "linux", "x64"] : selectedGuest === "windows-x64" ? ["self-hosted", "windows", "x64"] : ["self-hosted", "macos", "arm64"]; if (!worker || !selectedGuest || !digest) return <p role="alert">No immutable job image is configured for this guest platform.</p>; if (!worker.limits) return <div><p role="alert">Worker resource limits are not acknowledged yet. Return to Configure resources before creating a pool.</p><p>Configuring worker · resources in GiB</p><p>Trigger label: {label}</p><pre>runs-on: [{[...platformLabels, label].join(", ")}]</pre></div>; const resources = { vcpu: worker.limits.maxVcpuPerPod, memoryBytes: worker.limits.maxMemoryBytesPerPod, storageBytes: worker.limits.maxStorageBytesPerPod, concurrency: worker.limits.maxConcurrentPods }; return <form onSubmit={(e) => { e.preventDefault(); onCreate({ workerId: worker.id, guestPlatform: selectedGuest, name, triggerLabel: label, imageDigest: digest, resources }); }}><p>Configuring worker acknowledged. Resources are acknowledged; configure resources in GiB before creating the first enabled pool.</p>{guestPlatforms.length > 1 && <label>Guest platform<select value={selectedGuest} onChange={(e) => setGuestPlatform(e.target.value as typeof selectedGuest)}>{guestPlatforms.map((platform) => <option key={platform} value={platform}>{platform}</option>)}</select></label>}<label>Pool name<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Trigger label<input value={label} onChange={(e) => setLabel(e.target.value)} pattern="[a-z0-9][a-z0-9._-]{0,62}" /></label><p>Effective labels: <code>{[...platformLabels, label].join(", ")}</code></p><pre>runs-on: [{[...platformLabels, label].join(", ")}]</pre><button type="submit">Create pool</button></form>; }
function Complete({ detail }: { detail: OnboardingDetail }) { const [runnerRepository, setRunnerRepository] = useState<OnboardingDetail["github"]["repositories"][number] | null>(null); const approved = detail.github.repositories.find((r) => r.available && r.approved); const org = detail.organizations.find((o) => o.id === detail.github.organizationId); return <main className="onboarding"><section className="onboarding-card"><h1>Onboarding complete</h1><p>Organization: {org?.name ?? detail.github.organizationId}</p><p>Approved repositories: {detail.github.repositories.filter((r) => r.approved).length}</p><p>Worker: {detail.worker?.name ?? "Ready"}</p><p>Pool: {detail.pool?.name ?? "default"}</p><p>Effective labels: {detail.pool?.labels?.join(", ")}</p><pre>runs-on: [{detail.pool?.labels?.join(", ")}]</pre>{approved && <button type="button" className="button" onClick={() => setRunnerRepository(approved)}>Use Whitesmith runners</button>}<a className="button secondary" href="/">Open dashboard</a></section>{runnerRepository && detail.github.organizationId && <RunnerWorkflowPrModal organizationId={detail.github.organizationId} repositoryId={runnerRepository.id} repositoryName={runnerRepository.fullName} open onClose={() => setRunnerRepository(null)} />}</main>; }
