import { createHash, createPrivateKey, createSign, randomBytes } from "node:crypto";
import type { Sql } from "postgres";
import type { SecretBox } from "./auth.ts";
type SetupState = { purpose: string; userId: string|null; organizationId: string|null; idempotencyKey: string|null; encryptedState?: string; encryptedPkceVerifier?: string; expiresAt: number; consumedAt?: number };
type Installation = { organizationId: string|null; githubInstallationId:number; state:"pending"|"approved"|"suspended"; repositorySelection:string|null };
type Repository = { id:string; installationId:number; fullName:string; visibility:"private"|"internal"|"public"; available:boolean; approved:boolean };
type AppConfig = { id:number; slug:string; pem:string; clientSecret:string; webhookSecret:string };
type Fetcher = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
type DbLike = { sql?: Sql<{}>; setupStates?: Map<string, SetupState>; installations?: Map<number, Installation>; repositories?: Map<string, Repository>; appConfig?: AppConfig };
const API = "https://api.github.com";
export class GitHubAppService {
  private readonly db: DbLike; private readonly fetcher: Fetcher; private readonly box: SecretBox; private readonly baseUrl: string; private localConfig: AppConfig | undefined;
  constructor(opts: { db: DbLike | Sql<{}>; fetch?: Fetcher; secretBox: SecretBox; baseUrl: string }) { this.db=typeof opts.db==="function" ? {sql:opts.db} : opts.db; this.fetcher=opts.fetch ?? fetch; this.box=opts.secretBox; this.baseUrl=opts.baseUrl; if(!this.db.sql){ this.db.setupStates ??= new Map(); this.db.installations ??= new Map(); this.db.repositories ??= new Map(); } }
  private states() { return this.db.setupStates! as Map<string, SetupState>; }
  private async gh(path:string, init:RequestInit={}, jwt?:string): Promise<Record<string, unknown>> { const headers = new Headers(init.headers); headers.set("accept","application/vnd.github+json"); headers.set("x-github-api-version","2026-03-10"); if (jwt) headers.set("authorization",`Bearer ${jwt}`); const r=await this.fetcher(`${API}${path}`,{...init,headers}); if(!r.ok) throw new Error(`github_${r.status}`); const value: unknown=await r.json(); return value && typeof value==="object" ? value as Record<string,unknown> : {}; }
  private stateKey(raw:string) { return createHash("sha256").update(raw).digest("hex"); }
  private save(raw:string, value:SetupState) { this.states().set(this.stateKey(raw),value); }
  private consume(raw:string, userId:string, purpose:string) { const state=this.states().get(this.stateKey(raw)); if(!state || state.purpose!==purpose || state.userId!==userId || state.consumedAt || state.expiresAt<Date.now()) throw new Error("setup_state_expired"); state.consumedAt=Date.now(); return state; }
  async createManifestLaunch(userId: string, organizationId: string, idempotencyKey: string) {
    for (const state of this.states().values()) {
      if (state.purpose === "manifest" && state.userId === userId && state.organizationId === organizationId && state.idempotencyKey === idempotencyKey && !state.consumedAt && state.expiresAt > Date.now()) {
        return { action: `https://github.com/settings/apps/new?state=${this.box.decrypt(state.encryptedState!)}`, manifest: this.box.decrypt(state.encryptedPkceVerifier!) };
      }
    }
    const rawState = randomBytes(32).toString("base64url");
    const manifest = JSON.stringify({ name: "whitesmith", public: true, url: this.baseUrl, hook_attributes: { url: `${this.baseUrl}/api/github/webhooks`, active: true }, redirect_url: `${this.baseUrl}/api/github/app/manifest/callback`, setup_url: `${this.baseUrl}/api/github/app/setup`, description: "Whitesmith self-hosted GitHub Actions runners", callback_urls: [`${this.baseUrl}/api/github/app/callback`], default_permissions: { actions: "read", members: "read", organization_self_hosted_runners: "write", administration: "write" }, default_events: ["workflow_job", "installation", "installation_repositories"] });
    this.save(rawState, { purpose: "manifest", userId, organizationId, idempotencyKey, encryptedState: this.box.encrypt(rawState), encryptedPkceVerifier: this.box.encrypt(manifest), expiresAt: Date.now() + 600_000 });
    return { action: `https://github.com/settings/apps/new?state=${rawState}`, manifest };
  }
  async beginInstallation(userId:string, organizationId:string, idempotencyKey:string) { const slug=this.localConfig?.slug ?? this.db.appConfig?.slug ?? "whitesmith"; const cookie=randomBytes(32).toString("base64url"); this.save(cookie,{purpose:"install",userId,organizationId,idempotencyKey,encryptedState:this.box.encrypt(cookie),expiresAt:Date.now()+600000}); return {location:`https://github.com/apps/${slug}/installations/new`,installCookie:cookie}; }
  async completeManifestRegistration(userId:string,state:string,code:string) { const s=this.consume(state,userId,"manifest"); const result=await this.gh(`/app-manifests/${encodeURIComponent(code)}/conversions`,{method:"POST"}); const id=typeof result.id==="number"?result.id:0; const slug=typeof result.slug==="string"?result.slug:"whitesmith"; const pem=typeof result.pem==="string"?result.pem:""; const clientSecret=typeof result.client_secret==="string"?result.client_secret:""; const webhookSecret=typeof result.webhook_secret==="string"?result.webhook_secret:""; if(!id||!pem||!clientSecret||!webhookSecret) throw new Error("github_manifest_invalid"); this.localConfig={id,slug,pem:this.box.encrypt(pem),clientSecret:this.box.encrypt(clientSecret),webhookSecret:this.box.encrypt(webhookSecret)}; const install=randomBytes(32).toString("base64url"); this.save(install,{purpose:"install",userId,organizationId:s.organizationId,idempotencyKey:null,encryptedState:this.box.encrypt(install),expiresAt:Date.now()+600000}); return {location:`https://github.com/apps/${slug}/installations/new`,installCookie:install}; }
  private appJwt() { const config=this.localConfig ?? this.db.appConfig; const pem=config?.pem ? this.box.decrypt(config.pem) : ""; if(!pem) throw new Error("github_app_unconfigured"); const key=createPrivateKey(pem); const now=Math.floor(Date.now()/1000); const enc=(v:unknown)=>Buffer.from(JSON.stringify(v)).toString("base64url"); const input=`${enc({alg:"RS256",typ:"JWT"})}.${enc({iat:now-60,exp:now+540,iss:config?.id})}`; const sign=createSign("RSA-SHA256"); sign.update(input); return `${input}.${sign.sign(key).toString("base64url")}`; }
  async completeInstallation(userId:string, installCookie:string, installationId:number) { const s=this.consume(installCookie,userId,"install"); const info=await this.gh(`/app/installations/${installationId}`,{},this.appJwt()); const account=info.account && typeof info.account==="object" ? info.account as {type?:unknown;id?:unknown} : {}; if(account.type!=="Organization" || (s.organizationId && account.id && String(account.id)!==String(s.organizationId))) throw new Error("wrong_organization"); const token=await this.gh(`/app/installations/${installationId}/access_tokens`,{method:"POST"},this.appJwt()); const accessToken=typeof token.token==="string" ? token.token : ""; if(!accessToken) throw new Error("github_token_missing"); const repos=await this.gh(`/installation/repositories`,{headers:{authorization:`Bearer ${accessToken}`}}); const selection=typeof repos.repository_selection==="string" ? repos.repository_selection : null; const list=Array.isArray(repos.repositories) ? repos.repositories : []; this.db.installations!.set(installationId,{organizationId:s.organizationId,githubInstallationId:installationId,state:"approved",repositorySelection:selection}); await this.reconcileInstallationRepositories({installation:{id:installationId},repository_selection:selection,repositories_added:list}); }
  async reconcileInstallationRepositories(payload: unknown) { if (!payload || typeof payload !== "object") return; const data = payload as { installation?: { id?: number }; action?: string; repositories_removed?: Array<{id:number}>; repositories_added?: Array<{id:number;full_name:string;private?:boolean;visibility?:string}>; repositories?: Array<{id:number;full_name:string;private?:boolean;visibility?:string}> }; const id=Number(data.installation?.id); if(!id) return; const inst=this.db.installations!.get(id); if(data.action==="removed"||data.repositories_removed) for(const r of data.repositories_removed??[]) { const x=this.db.repositories!.get(String(r.id)); if(x)x.available=false; } for(const r of data.repositories_added??data.repositories??[]) { const visibility=(r.visibility==="private"||r.visibility==="internal"||r.visibility==="public")?r.visibility:(r.private?"private":"public"); this.db.repositories!.set(String(r.id),{id:String(r.id),installationId:id,fullName:r.full_name,visibility,available:true,approved:false}); } if(inst && (data.action==="deleted"||data.action==="suspended")) inst.state="suspended"; }
  async getWebhookSecret() { const config=this.localConfig ?? this.db.appConfig; return config?.webhookSecret ? this.box.decrypt(config.webhookSecret) : null; }
}
