import { createHash, randomBytes } from "node:crypto";
import type { Sql } from "postgres";
import { SecretBox } from "./auth.ts";

export interface OAuthState { state: string; verifier: string; createdAt: number; }
export function createPkce(): OAuthState { const verifier = randomBytes(32).toString("base64url"); const state = randomBytes(32).toString("base64url"); return { state, verifier, createdAt: Date.now() }; }
export function pkceChallenge(verifier: string): string { return createHash("sha256").update(verifier).digest("base64url"); }
export function githubAuthorizeUrl(base: string, clientId: string, flow: OAuthState): string { const u = new URL("https://github.com/login/oauth/authorize"); u.searchParams.set("client_id", clientId); u.searchParams.set("redirect_uri", `${base}/api/auth/github/callback`); u.searchParams.set("scope", "read:user read:org"); u.searchParams.set("state", flow.state); u.searchParams.set("code_challenge", pkceChallenge(flow.verifier)); u.searchParams.set("code_challenge_method", "S256"); return u.toString(); }
export interface OAuthUser { id: number; login: string; accessToken: string; }
export interface GithubOrganization { id: number; login: string; }
export async function exchangeOAuth(code: string, state: OAuthState, clientId: string, clientSecret: string, base: string): Promise<OAuthUser> { if (Date.now() - state.createdAt > 10 * 60_000) throw new Error("oauth state expired"); const response = await fetch("https://github.com/login/oauth/access_token", { method: "POST", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify({ client_id: clientId, client_secret: clientSecret, code, redirect_uri: `${base}/api/auth/github/callback`, code_verifier: state.verifier }) }); if (!response.ok) throw new Error("oauth exchange failed"); const token = (await response.json() as { access_token?: string }).access_token; if (!token) throw new Error("oauth token missing"); const userResponse = await fetch("https://api.github.com/user", { headers: { authorization: `Bearer ${token}`, accept: "application/vnd.github+json", "user-agent": "whitesmith-control-plane" } }); if (!userResponse.ok) throw new Error("github user lookup failed"); const user = await userResponse.json() as { id:number;login:string }; return { ...user, accessToken: token }; }
export async function listGithubOrganizations(accessToken: string): Promise<GithubOrganization[]> { const response = await fetch("https://api.github.com/user/orgs?per_page=100", { headers: { authorization: `Bearer ${accessToken}`, accept: "application/vnd.github+json", "user-agent": "whitesmith-control-plane" } }); if (!response.ok) throw new Error("github organization lookup failed"); const organizations = await response.json() as Array<{ id?: number; login?: string }>; return organizations.filter((organization): organization is GithubOrganization => typeof organization.id === "number" && typeof organization.login === "string" && organization.login.length > 0); }
export async function syncGithubOrganizations(sql: Sql<{}>, userId: string, accessToken: string): Promise<void> { const organizations = await listGithubOrganizations(accessToken); await sql.begin(async tx => { for (const organization of organizations) { const [row] = await tx`insert into organizations (github_org_id,login) values (${organization.id},${organization.login}) on conflict (github_org_id) do update set login=excluded.login returning id`; await tx`insert into memberships (organization_id,user_id,role) values (${row.id},${userId},'member') on conflict (organization_id,user_id) do update set role=excluded.role`; } }); }
export async function ensureBootstrapAdmin(sql: Sql<{}>, githubId: number, login: string, allowlisted: string): Promise<void> { if (login.toLowerCase() !== allowlisted.trim().toLowerCase()) throw new Error("bootstrap login mismatch"); await sql`update users set is_global_admin=true where github_user_id=${githubId}`; }
export function encryptGithubSecret(box: SecretBox, value: string): string { return box.encrypt(value); }
