import { PoolResources, WorkerLimits } from "@whitesmith/contracts";
export interface Candidate { worker: { admissionState:string; connectionState:string; configurationState:string; limits: unknown }; pool: { enabled:boolean; resources:unknown; concurrency:number; active:number; labels:string[]; triggerLabel:string|null }; requestedLabels:string[]; }
export function labelsMatch(requestedLabels: readonly string[], poolLabels: readonly string[], triggerLabel: string|null): boolean {
  if (!triggerLabel) return false;
  const requested = new Set(requestedLabels.map((label) => label.toLowerCase()));
  const labels = new Set(poolLabels.map((label) => label.toLowerCase()));
  return requested.has(triggerLabel.toLowerCase()) && [...requested].every((label) => labels.has(label));
}
export function fits(candidate: Candidate): boolean { if (!labelsMatch(candidate.requestedLabels, candidate.pool.labels, candidate.pool.triggerLabel)) return false; if (candidate.worker.admissionState !== "adopted" || candidate.worker.connectionState !== "online" || candidate.worker.configurationState !== "ready" || !candidate.pool.enabled || candidate.pool.active >= candidate.pool.concurrency) return false; const limits = WorkerLimits.safeParse(candidate.worker.limits); const resources = PoolResources.safeParse(candidate.pool.resources); if (!limits.success || !resources.success) return false; return resources.data.vcpu <= limits.data.maxVcpuPerPod && resources.data.memoryBytes <= limits.data.maxMemoryBytesPerPod && resources.data.storageBytes <= limits.data.maxStorageBytesPerPod && resources.data.concurrency <= limits.data.maxConcurrentPods; }
export function reason(candidate: Candidate): string { if (!labelsMatch(candidate.requestedLabels, candidate.pool.labels, candidate.pool.triggerLabel)) return "no_matching_labels"; if (candidate.worker.admissionState !== "adopted") return "worker_pending_adoption"; if (candidate.worker.connectionState !== "online") return "worker_offline"; if (candidate.worker.configurationState !== "ready") return "worker_not_ready"; if (!candidate.pool.enabled) return "pool_disabled"; if (candidate.pool.active >= candidate.pool.concurrency) return "pool_concurrency"; return fits(candidate) ? "admissible" : "resource_ceiling"; }
