import { randomBytes } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import type { GuestPlatform, PoolResources } from "@whitesmith/contracts";
import type { Lease, RuntimeDriver, RuntimeLease } from "./runtime.ts";
type RunPowerShell = (script: string, args: string[]) => Promise<string>;
export type HyperVConfig = { windowsVhdx: string; windowsImageDigest: string; linuxVhdx?: string; linuxImageDigest?: string; switchName?: string; maxJobRuntimeMs?: number; runPowerShell?: RunPowerShell };
const defaultPowerShell: RunPowerShell = async (script, args) => { const proc = Bun.spawn(["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", script, ...args], { stdout: "pipe", stderr: "pipe" }); const output = await new Response(proc.stdout).text(); if (await proc.exited !== 0) throw new Error(await new Response(proc.stderr).text()); return output; };
export class HyperVDriver implements RuntimeDriver {
  readonly name = "windows-hyperv" as const;
  private readonly run: RunPowerShell;
  private readonly config: Required<Pick<HyperVConfig, "switchName" | "maxJobRuntimeMs">> & HyperVConfig;
  private readonly active = new Map<string, RuntimeLease>();
  constructor(config: HyperVConfig) { if (!config.windowsVhdx || !config.windowsImageDigest) throw new Error("Windows Hyper-V template is required"); if ((config.linuxVhdx && !config.linuxImageDigest) || (!config.linuxVhdx && config.linuxImageDigest)) throw new Error("Linux Hyper-V template and digest must be configured together"); this.config = { ...config, switchName: config.switchName ?? Bun.env.WHITESMITH_HYPERV_SWITCH ?? "Default Switch", maxJobRuntimeMs: config.maxJobRuntimeMs ?? Number(Bun.env.WHITESMITH_MAX_JOB_RUNTIME_MS ?? 86_400_000) }; this.run = config.runPowerShell ?? defaultPowerShell; }
  validatePool(resources: PoolResources): void { if (resources.vcpu < 1 || resources.memoryBytes < 1 || resources.storageBytes < 1) throw new Error("invalid Hyper-V pool resources"); }
  async reserveCapacity(_resources: PoolResources): Promise<void> { await this.run("Get-VMSwitch -Name $args[0] -ErrorAction Stop", [this.config.switchName]); }
  private template(lease: Lease): string { if (lease.imageDigest === this.config.windowsImageDigest) return this.config.windowsVhdx; if (lease.imageDigest === this.config.linuxImageDigest && this.config.linuxVhdx) return this.config.linuxVhdx; throw new Error("immutable job image is not configured for this guest platform"); }
  async createLease(lease: Lease): Promise<RuntimeLease> { const existing = this.active.get(lease.id); if (existing) return existing; this.validatePool(lease.resources); const parent = this.template(lease); const vmName = `Whitesmith-${lease.id}`; const root = `${Bun.env.ProgramData ?? "C:\\ProgramData"}\\Whitesmith\\leases\\${lease.id}`; const disk = `${root}\\job.vhdx`; await mkdir(root, { recursive: true }); await this.run("New-VHD -Path $args[0] -ParentPath $args[1] -Differencing | Out-Null; New-VM -Name $args[2] -Generation 2 -MemoryStartupBytes $args[3] -SwitchName $args[4] -VHDPath $args[0] | Out-Null; Set-VM -Name $args[2] -CheckpointType Disabled -ProcessorCount $args[5]; Enable-VMIntegrationService -VMName $args[2] -Name 'Guest Service Interface'; Start-VM -Name $args[2] | Out-Null", [disk, parent, vmName, String(lease.resources.memoryBytes), this.config.switchName, String(lease.resources.vcpu)]); const bootstrap = { version: 1 as const, leaseId: lease.id, nonce: lease.nonce, encodedJitConfig: lease.encodedJitConfig, callbackUrl: `http://127.0.0.1:27182/v1/leases/${lease.id}/complete`, callbackToken: randomBytes(32).toString("base64url") }; const bootstrapPath = `${root}\\bootstrap.json`; await writeFile(bootstrapPath, JSON.stringify(bootstrap)); try { await this.run("Copy-VMFile -Name $args[0] -SourcePath $args[1] -DestinationPath $args[2] -FileSource Host -CreateFullPath -Force", [vmName, bootstrapPath, "C:\\ProgramData\\Whitesmith\\bootstrap.json"]); } finally { await unlink(bootstrapPath).catch(() => undefined); } const runtime: RuntimeLease = { runtimeInstanceId: vmName, observed: { vcpu: lease.resources.vcpu, memoryBytes: lease.resources.memoryBytes, storageBytes: lease.resources.storageBytes }, state: "sandbox_attested", completion: this.waitForCompletion(lease.id) }; this.active.set(lease.id, runtime); return runtime; }
  private async waitForCompletion(_leaseId: string): Promise<number> { await Bun.sleep(this.config.maxJobRuntimeMs); return 0; }
  async inspectLease(leaseId: string): Promise<RuntimeLease> { const runtime = this.active.get(leaseId); if (!runtime) throw new Error("Hyper-V lease not found"); return runtime; }
  async stopLease(leaseId: string): Promise<void> { await this.run("Stop-VM -Name $args[0] -Force -ErrorAction SilentlyContinue", [`Whitesmith-${leaseId}`]); }
  async removeLease(leaseId: string): Promise<void> { await this.run("Remove-VM -Name $args[0] -Force -ErrorAction SilentlyContinue", [`Whitesmith-${leaseId}`]); this.active.delete(leaseId); }
  async collectDiagnostics(leaseId: string): Promise<Record<string, unknown>> { return { leaseId, driver: this.name, switchName: this.config.switchName }; }
}
