import { createPrivateKey, generateKeyPairSync, sign } from "node:crypto";
import { hostname } from "node:os";

export interface MacWorkerLimits { maxVcpuPerPod: number; maxMemoryBytesPerPod: number; maxStorageBytesPerPod: number; maxConcurrentPods: number }
export interface MacWorkerJoinInput { code: string; publicKey: string; vmUuid: string; limits: MacWorkerLimits }
export interface MacWorkerJoinPayload extends MacWorkerJoinInput { platform: "macos-arm64" }
export function buildMacWorkerJoinPayload(input: MacWorkerJoinInput): MacWorkerJoinPayload { return { ...input, platform: "macos-arm64" }; }
export function buildMacWorkerSocketUrl(base: string, workerId: string): string { const url = new URL(base); url.protocol = url.protocol === "https:" ? "wss:" : "ws:"; url.pathname = "/api/v1/workers/connect"; url.search = new URLSearchParams({ workerId }).toString(); return url.toString(); }
function createKeyPair(): { privateKey: string; publicKey: string } { const pair = generateKeyPairSync("ed25519"); return { privateKey: pair.privateKey.export({ format: "pem", type: "pkcs8" }).toString(), publicKey: pair.publicKey.export({ format: "pem", type: "spki" }).toString() }; }
async function readJoinCode(): Promise<Buffer> { const reader = Bun.stdin.stream().getReader(); const { value } = await reader.read(); reader.releaseLock(); const code = Buffer.from(value ?? []); if (!code.toString("utf8").trim()) throw new Error("join code required on stdin"); return code; }
export async function runMacWorker(baseUrl: string, limits: MacWorkerLimits): Promise<never> { const key = createKeyPair(); const codeBytes = await readJoinCode(); const code = codeBytes.toString("utf8").trim(); const vmUuid = Bun.env.WHITESMITH_VM_UUID ?? hostname(); const response = await fetch(new URL("/api/workers/join", baseUrl), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(buildMacWorkerJoinPayload({ code, publicKey: key.publicKey, vmUuid, limits })) }); codeBytes.fill(0); if (!response.ok) throw new Error(`worker join failed: ${response.status} ${await response.text()}`); const joined = await response.json() as { workerId: string; fingerprint: string }; const socket = new WebSocket(buildMacWorkerSocketUrl(baseUrl, joined.workerId)); await new Promise<void>((resolve, reject) => { socket.addEventListener("open", () => resolve()); socket.addEventListener("error", () => reject(new Error("worker websocket failed"))); }); socket.addEventListener("message", event => { const message = JSON.parse(String(event.data)) as { type?: string; nonce?: string }; if (message.type === "challenge" && message.nonce) { const signature = sign(null, Buffer.from(message.nonce, "base64url"), createPrivateKey(key.privateKey)).toString("base64url"); socket.send(JSON.stringify({ type: "authenticate", workerId: joined.workerId, signature })); } if (message.type === "authenticated") socket.send(JSON.stringify({ version: 1, type: "doctor", workerId: joined.workerId, payload: { platform: "macos-arm64", driver: "tart-vm", vmUuid, vcpu: limits.maxVcpuPerPod, memoryBytes: limits.maxMemoryBytesPerPod, storageBytes: limits.maxStorageBytesPerPod, maxConcurrentPods: limits.maxConcurrentPods } })); if (message.type === "ping") socket.send(JSON.stringify({ type: "pong" })); }); socket.addEventListener("close", () => process.exit(1)); return await new Promise<never>(() => undefined); }
if (import.meta.main && Bun.argv[2] === "mac-worker") { const baseUrl = Bun.env.WHITESMITH_CONTROL_PLANE_URL; if (!baseUrl) throw new Error("WHITESMITH_CONTROL_PLANE_URL is required"); await runMacWorker(baseUrl, { maxVcpuPerPod: Number(Bun.env.MAX_VCPU_PER_POD ?? 2), maxMemoryBytesPerPod: Number(Bun.env.MAX_MEMORY_BYTES_PER_POD ?? 4 * 1024 ** 3), maxStorageBytesPerPod: Number(Bun.env.MAX_STORAGE_BYTES_PER_POD ?? 20 * 1024 ** 3), maxConcurrentPods: Number(Bun.env.MAX_CONCURRENT_PODS ?? 1) }); }
