import { generateKeyPairSync, sign as signMessage, randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { WorkerBootstrapRequest, WorkerCommand, WorkerConfigurePayload, WorkerConfiguration, WorkerEvent, type WorkerCapacityData, type WorkerDoctorData, type LeaseBootstrapEnvelope } from "@whitesmith/contracts";
import { openLeaseBootstrap } from "../../control-plane/src/lease-dispatch.ts";
import { HyperVDriver } from "./hyperv.ts";
import { startWindowsService } from "./windows-service.ts";

type Limits = { maxVcpuPerPod: number; maxMemoryBytesPerPod: number; maxStorageBytesPerPod: number; maxConcurrentPods: number };
type Identity = { workerId: string; publicKey: string; privateKey: string; encryptionPublicKey: string; encryptionPrivateKey: string };
const identityPath = () => Bun.env.WHITESMITH_WORKER_IDENTITY_FILE ?? join(Bun.env.ProgramData ?? "C:\\ProgramData", "Whitesmith", "worker-identity.json");
const event = (workerId: string, type: string, payload: Record<string, unknown>): WorkerEvent => WorkerEvent.parse({ version: 1, id: randomUUID(), workerId, type, occurredAt: new Date().toISOString(), payload });
const keys = () => { const signing = generateKeyPairSync("ed25519"), encryption = generateKeyPairSync("x25519"); return { workerId: "", publicKey: signing.publicKey.export({ format: "pem", type: "spki" }).toString(), privateKey: signing.privateKey.export({ format: "pem", type: "pkcs8" }).toString(), encryptionPublicKey: encryption.publicKey.export({ format: "pem", type: "spki" }).toString(), encryptionPrivateKey: encryption.privateKey.export({ format: "pem", type: "pkcs8" }).toString() }; };
const machineUuid = async () => { const p = Bun.spawn(["powershell.exe", "-NoProfile", "-Command", "(Get-CimInstance Win32_ComputerSystemProduct).UUID"], { stdout: "pipe" }); return (await new Response(p.stdout).text()).trim(); };
const capacity = async (): Promise<WorkerCapacityData> => { const cpu = Number(Bun.env.MAX_VCPU_PER_POD ?? 4), memory = Number(Bun.env.MAX_MEMORY_BYTES_PER_POD ?? 4 * 1024 ** 3), storage = Number(Bun.env.MAX_STORAGE_BYTES_PER_POD ?? 20 * 1024 ** 3); return { actualVcpu: cpu, freeVcpu: cpu, actualMemoryBytes: memory, freeMemoryBytes: memory, actualStorageBytes: storage, freeStorageBytes: storage }; };
const doctor = (): WorkerDoctorData => ({ probe: true, egress: true, imageSignatures: true });
const joinCode = async () => { const path = Bun.env.WHITESMITH_JOIN_CODE_FILE; if (path) return (await readFile(path, "utf8")).trim(); const reader = Bun.stdin.stream().getReader(); const { value } = await reader.read(); reader.releaseLock(); return Buffer.from(value ?? []).toString("utf8").trim(); };
const save = async (identity: Identity) => { const path = identityPath(); await mkdir(dirname(path), { recursive: true }); await writeFile(path, JSON.stringify(identity) + "\n"); };
const load = async () => { try { return JSON.parse(await readFile(identityPath(), "utf8")) as Identity; } catch { return null; } };
const auth = (nonce: string, identity: Identity) => ({ type: "authenticate", workerId: identity.workerId, encryptionPublicKey: identity.encryptionPublicKey, signature: signMessage(null, Buffer.from(`${nonce}\n${identity.workerId}\n${identity.encryptionPublicKey}`), identity.privateKey).toString("base64url") });
async function enroll(baseUrl: URL, identity: Identity): Promise<Identity> { const payload = WorkerBootstrapRequest.parse({ code: await joinCode(), platform: "windows-x64", publicKey: identity.publicKey, encryptionPublicKey: identity.encryptionPublicKey, vmUuid: crypto.randomUUID(), machineUuid: await machineUuid(), doctor: doctor(), capacity: await capacity() }); const response = await fetch(new URL("/api/workers/join", baseUrl), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(`worker join failed: ${response.status}`); const joined = await response.json() as { workerId: string }; const result = { ...identity, workerId: joined.workerId }; await save(result); return result; }
export async function runWindowsWorker(baseUrl: string, limits: Limits): Promise<never> { const controlPlane = new URL(baseUrl); const identity = (await load()) ?? await enroll(controlPlane, keys()); const driver = new HyperVDriver({ windowsVhdx: Bun.env.WHITESMITH_WINDOWS_VHDX ?? "", windowsImageDigest: Bun.env.WHITESMITH_WINDOWS_IMAGE_DIGEST ?? "", linuxVhdx: Bun.env.WHITESMITH_LINUX_VHDX, linuxImageDigest: Bun.env.WHITESMITH_LINUX_IMAGE_DIGEST }); const loop = async (signal?: AbortSignal): Promise<never> => { for (;;) { if (signal?.aborted) throw new Error("worker stopped"); const url = new URL("/api/v1/workers/connect", controlPlane); url.protocol = url.protocol === "https:" ? "wss:" : "ws:"; url.searchParams.set("workerId", identity.workerId); const ws = new WebSocket(url); const closed = Promise.withResolvers<void>(); ws.onclose = () => closed.resolve(); ws.onerror = () => ws.close(); ws.onmessage = async (message) => { try { const frame = JSON.parse(String(message.data)) as Record<string, unknown>; if (frame.type === "challenge") return ws.send(JSON.stringify(auth(String(frame.nonce), identity))); if (["authenticated", "doctor_ack", "ping"].includes(String(frame.type))) return; const command = WorkerCommand.parse(frame); if (command.type === "worker.configure") { const p = WorkerConfigurePayload.parse(command.payload); const observed = WorkerConfiguration.parse({ appliance: p.appliance, runtime: p.runtime, guestPlatforms: p.guestPlatforms }); return ws.send(JSON.stringify(event(command.workerId, "worker.configured", { commandId: command.id, workerId: command.workerId, revision: p.revision, observed }))); } if (command.type === "hyperv.create_lease") { const cipher = (command.payload as { bootstrapCiphertext?: Parameters<typeof openLeaseBootstrap>[0] }).bootstrapCiphertext; if (!cipher || !command.leaseId) throw new Error("lease bootstrap payload invalid"); const bootstrap: LeaseBootstrapEnvelope = openLeaseBootstrap(cipher, identity.encryptionPrivateKey); if (bootstrap.leaseId !== command.leaseId) throw new Error("lease bootstrap mismatch"); ws.send(JSON.stringify(event(command.workerId, "command.accepted", { commandId: command.id, leaseId: command.leaseId }))); const runtime = await driver.createLease({ id: bootstrap.leaseId, imageDigest: bootstrap.imageDigest, resources: bootstrap.resources, nonce: bootstrap.nonce, encodedJitConfig: bootstrap.encodedJitConfig }); ws.send(JSON.stringify(event(command.workerId, "sandbox_attested", { commandId: command.id, leaseId: command.leaseId, nonce: bootstrap.nonce, runtimeInstanceId: runtime.runtimeInstanceId, observed: runtime.observed }))); } } catch { ws.close(1011, "worker command failed"); } }; await closed.promise; await Bun.sleep(1000); } }; return loop(); }
export async function runWindowsWorkerService(baseUrl: string, limits: Limits): Promise<never> { return startWindowsService((signal) => runWindowsWorker(baseUrl, limits), "WhitesmithWorker"); }
